version: '3.5'

services:
  db:
    # container_name: postgresdb
    image: postgres:15.2-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    ports:
      - 5432:5432
