version: '3.5'

services:
  db:
    container_name: postgresdb
    image: postgres:15.2-alpine
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: exchange
      POSTGRES_DB: exchangedb
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432
    networks:
      - database

networks:
  database:
    driver: bridge
volumes:
  postgres:
